### ISSUE TITLE
Order of ellipsis and dot

### ISSUE THREAD

**Issue by samwilson** [standardebooks/g-k-chesterton_the-napoleon-of-notting-hill#1]
I think the last ellipsis and full stop in this passage should be the other way around:

```
“What can it be? What can it be? What will London be like a century hence?
Is there anything we have not thought of? Houses upside down⁠—more hygienic,
perhaps? Men walking on hands⁠—make feet flexible, don’t you know?
Moon … motorcars … no heads. …”
```

i.e. `motorcars … no heads … .”`

Or something. I'm sure someone with more typographical knowledge than me will know. It's just that the current way around looks odd to me.

**Comment by acabal** [comment]
Formatting ellipses that way is our house style, because typically books just put four spaced periods in a row, so it's not possible to tell which period is the sentence full stop, and which one is part of the ellipses.  (Or if there was even meant to be a difference.)

When formatted in our style, the period and ellipses emulate the appearance of print books for most fonts.  Some fonts have tighter ellipses spacing and might look a bit stranger, but most of the time it looks fine.

**Comment by samwilson** [comment]
No worries! Thanks for replying.

On my Kobo it looks like this:

[![Kobo](https://c1.staticflickr.com/5/4272/34108149533_5405c85a84_c.jpg)](https://flic.kr/p/TY2bxF)

**Comment by acabal** [comment]
What version of the Kobo software are you using there?  That looks like the Kobo might not be able to hyphenate words and is having a hard time kerning correctly.  You can see in the source that it's just "full stop, hair space, ellipses" which shouldn't be a problem.

Maybe if you can update your Kobo, the problem might be solved?  I haven't experienced problems like that yet on my Kobo, which is latest-gen and up-to-date.

**Comment by samwilson** [comment]
Yes, you're right, I'm running an old version: 3.4.1 (5/25/14).

I'll try to find a Windows machine so I can run the upgrade, and see if things are fixed.
